# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20150907_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationslot',
            name='out_of_state',
            field=models.BooleanField(default=False, verbose_name='In State?'),
        ),
    ]
