# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservationslot_out_of_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationslot',
            name='last_scanned',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservationslot',
            name='last_scanned_on_time',
            field=models.NullBooleanField(),
        ),
    ]
