# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-06 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20160912_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationslot',
            name='out_of_state',
        ),
        migrations.AddField(
            model_name='reservationslot',
            name='assisted',
            field=models.BooleanField(default=False, verbose_name='assisted?'),
        ),
    ]
