# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-21 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20160912_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationslot',
            name='assisted_move_in',
            field=models.BooleanField(default=False, verbose_name='Assisted Move In?'),
        ),
    ]
