# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-23 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_reservationslot_assisted_move_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationslot',
            name='assisted_move_in',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='assisted_move_in',
            field=models.BooleanField(default=False, verbose_name='Assisted Move In?'),
        ),
    ]
