# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160518_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinparkinguser',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='zones.Building'),
        ),
    ]
