# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='application_term',
            field=models.CharField(choices=[('FA', 'Fall'), ('WI', 'Winter'), ('SP', 'Spring'), ('SU', 'Summer')], default='FA', max_length=2),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='application_year',
            field=models.PositiveSmallIntegerField(default=2016),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='term_code',
            field=models.PositiveSmallIntegerField(default='2166', verbose_name='Term Code'),
        ),
    ]
