# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20160702_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='reservation_close_day',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
