# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_adminsettings_reservation_close_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='reservation_close_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
