# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20160710_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsettings',
            name='reservation_open',
        ),
    ]
