# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_adminsettings_reservation_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='term_code',
            field=models.PositiveSmallIntegerField(default='2178', verbose_name='Term Code'),
        ),
    ]
