# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-21 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_auto_20160912_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='application_year',
            field=models.PositiveSmallIntegerField(default=2017),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='term_code',
            field=models.PositiveSmallIntegerField(default='2176', verbose_name='Term Code'),
        ),
    ]
