# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-05 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20170721_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='term_code',
            field=models.PositiveSmallIntegerField(default=2178, verbose_name='Term Code'),
        ),
    ]
